### ISSUE TITLE
Get sensor data return only zeros

### ISSUE THREAD

**Issue by vincentrou** [Adlink-ROS/bmi160_spi_demo#1]
The sample code works with the test returning "OK" but when getting data it returns only zeros.

Here is the code I used : https://github.com/vincentrou/bmi160_spi_demo/blob/main/main.c

It was tested on an Adlink ROS pico NX.

**Comment by cwyark** [comment]
@vincentrou  Thanks for reporting. I'll check this in these days.

**Comment by vincentrou** [comment]
Any update on this ?
For your information here is the result of the code used :
```
   Chip ID 0xD1
   OK
   OK get data ; ax:0   ay:0    az:0
   OK get data ; ax:0   ay:0    az:0
   OK get data ; ax:0   ay:0    az:0
   OK get data ; ax:0   ay:0    az:0
   OK get data ; ax:0   ay:0    az:0
   OK get data ; ax:0   ay:0    az:0
   ...
```

**Comment by DanielHo-BS** [comment]
@vincentrou Thanks for reporting. The issue has fixed now.
There was some problems about spi_transfer and spi_write. Too fast to load the data, so need to add delay time when writing.

Now, we update the file "main.c ", please check it. Have a good day!
